### PR TITLE
Add location_id to users schema

### PR DESCRIPTION
**Pull request by awhlam**
Add `location_id` field to `users` schema for PR #7

### CODE REVIEW

**Review by fernanda1411 — CHANGES_REQUESTED** [review]
How do you feel about having a separate file for the user table schema as its used on different domains? That would make it easier to maintain it. I imagine we will need to make more changes to the users when working on the signup/login stuff as we might need to add email, password hash, etc.

**Comment by awhlam** [comment]
> How do you feel about having a separate file for the user table schema as its used on different domains? That would make it easier to maintain it. I imagine we will need to make more changes to the users when working on the signup/login stuff as we might need to add email, password hash, etc.

Sounds good to me. Will update this PR today

**Comment by awhlam** [comment]
> How do you feel about having a separate file for the user table schema as its used on different domains? That would make it easier to maintain it. I imagine we will need to make more changes to the users when working on the signup/login stuff as we might need to add email, password hash, etc.

@fernanda1411 - Sounds good. I updated this PR with the users schema split out, let me know if that works for you.

**Review by fernanda1411 — APPROVED** [review]
Sounds good to me :) Thanks for the change

**Pull request merged**
